### ISSUE TITLE
Presents/Series logic not working properly

### ISSUE THREAD

**Issue by alexgreen** [TheTyee/design-article.thetyee.ca#204]
On this Tyee Presents Series you can see that both the Series badge and the Presents badge are appearing and overlapping each other:
http://preview.thetyee.ca/Presents/2016/06/09/Start-Farmers-Market/index.html

In the repo this does not occur:
http://thetyee.github.io/design-article.thetyee.ca/presents-series
...because there's the following logic in article-header.html to prevent a multi-badge collision:

```
        {% if page.presents == true %}

            {% include 00-atoms/images/presents-badge.html badge-position="badge--headline-placement badge--headline-placement--presents" %}
            <h6 class="tyee-presents-label"><a href="#">Events, contests and other initiatives by The Tyee and select partners.</a></h6>

        {% elsif page.series == true %}

            {% include 00-atoms/images/series-badge.html series-badge-position="badge--headline-placement" %}
            <h6 class="category-label"><a href="#" data-bind="category">{{ page.meta-category }}</a></h6>

        {% else %}

            <h6 class="category-label"><a href="#" data-bind="category">{{ page.meta-category }}</a></h6>

        {% endif %}

```

When an article is both a Presents story and also part of a Series, then only the Presents badge should be shown. Doesn't seem like this logic is working in preview.

**Comment by MrBryan** [comment]
I didn't think of that, have to do the equivalent logic in bric.. Will do

**Comment by MrBryan** [comment]
fixed as with referenced issue

**Comment by alexgreen** [comment]
This issue is still evident on the preview page:
http://preview.thetyee.ca/Presents/2016/06/09/Start-Farmers-Market/index.html

**Comment by phillipadsmith** [comment]
Re-previewed and it does appear to still be there:
http://preview.thetyee.ca/Presents/2016/06/09/Start-Farmers-Market/

**Comment by MrBryan** [comment]
Sorry fixed the logic, gone for reals

http://preview.thetyee.ca/Presents/2016/06/09/Start-Farmers-Market/index.html
