### ISSUE TITLE
Arrow is missing in read-more link of related story blocks

### ISSUE THREAD

**Issue by alexgreen** [TheTyee/design-article.thetyee.ca#220]
Missing here: http://preview.thetyee.ca/News/2016/06/22/BC-Ban-Big-Bucks/

Should be like here: http://thetyee.github.io/design-article.thetyee.ca/library

**Comment by MrBryan** [comment]
Fixed going forward. Repreviewed that story http://preview.thetyee.ca/News/2016/06/22/BC-Ban-Big-Bucks/

ec21666

**Comment by alexgreen** [comment]
Arrows are still missing from live site:

http://thetyee.ca/News/2016/06/22/BC-Ban-Big-Bucks/
http://thetyee.ca/News/2015/02/23/Four-Sisters-Coop-Profile/

**Comment by alexgreen** [comment]
This still hasn't been deployed. Any word @MrBryan ?

**Comment by MrBryan** [comment]
Sorry I had put it into a template but it wasn't deployed properly on git. Fixed now for stories going forward / republished

**Comment by MrBryan** [comment]
deployed properly in bricolage I meant

**Comment by alexgreen** [comment]
You often say stories need to be "republished" before design changes will take effect. Do you mean that Bricolage generates a website of static pages and these static pages only get generated when someone pushes a "publish" button for each individual story? Doesn't bric regenerate all pages when it notices a change in the source files? If not then isn't there a "republish all stories" button?

**Comment by phillipadsmith** [comment]
> You often say stories need to be "republished" before design changes will take effect. Do you mean that Bricolage generates a website of static pages and these static pages only get generated when someone pushes a "publish" button for each individual story? Doesn't bric regenerate all pages when it notices a change in the source files? If not then isn't there a "republish all stories" button?

Hey there Alex,

Yes, indeed, Bricolage generates static files -- it is one of the original "static website generators." 

The static pages are created when a story is published, and at that time the story content is merged with the template code to produce the final HTML.

However, the template code can contain includes, so some changes (to includes) propogate across the entire site immediately.

Those changes that are not in includes require re-publishing all stories.

However, The Tyee is made up of 15,000+ stories, thus a "republish all stories" button is not technically feasible, because it would bring the system to a grind and would often ,block the publishing of more pressing stories. 

So republishing the entire site is a slow and time-consuming operation. Thus, it's helpful to batch work that requires this.

Hope that helps a bit.

**Comment by alexgreen** [comment]
Thanks for the info. That makes sense. Sounds like the best option would be if bric could be set to auto-republish in batches during downtimes of low activity (maybe 2:30–5:30 am).
