### ISSUE TITLE
Handle "Full Width" element (~20-30 stories total?)

### ISSUE THREAD

**Issue by phillipadsmith** [TheTyee/design-article.thetyee.ca#252]
@MrBryan Some stories in the past used a "full width" element to break out of the two-column layout at the top of the story, typically for a very large illustration, map, or interactive. 

Here's one example:
http://thetyee.ca/Opinion/2016/05/24/UBC-Let-Students-Live-on-Campus/

On the preview site that illustration is cropped incorrectly.

This would be another interesting story to check:
http://thetyee.ca/News/2012/07/04/CarbonFootprint/

In fact, all "full width" containing stories should get checked manually, I would propose. 

Not launch-blocking, but problematic.

**Comment by phillipadsmith** [comment]
Related, the "caption" element for this sub-element is probably different than the standard one, e.g.: nothing is appearing here: http://preview.thetyee.ca/Opinion/2016/05/24/UBC-Let-Students-Live-on-Campus/

**Comment by phillipadsmith** [comment]
Another full width example, I think:
Side-by-side photo spacing
URL: http://preview.thetyee.ca/News/2016/05/25/Rise-of-Condos-Razed-Trees-Bird-Evictions/
Description: This story has side by side photos as the main art, and it’s creating an odd spacing issue with too much white space on top and bottom
Reporter: Jeanette

**Comment by MrBryan** [comment]
Jeanette's one is that the image itself has a bunch of white space in it. ( so it just needs to be cropped differently i.e. without white space included)

**Comment by MrBryan** [comment]
For the other one, the full width zone is going to have to be parsed, it's actually written in with html in the element  

![image](https://cloud.githubusercontent.com/assets/1721891/16738988/20d926a4-4766-11e6-98f1-411a6074e650.png)

**Comment by MrBryan** [comment]
Repreviewing  the first one removed the empty quote which was fixed earlier

**Comment by phillipadsmith** [comment]
> Repreviewing the first one removed the empty quote which was fixed earlier

Not totally sure which one you're referring to here, but I'm still not seeing a caption under this image:
http://preview.thetyee.ca/Opinion/2016/05/24/UBC-Let-Students-Live-on-Campus/

In terms of the HTML in the full-width zone: Yes, that's correct, it was a kludge of a solution at the time ... and it's possible that those will need to be manually updated (as mentioned, I don't believe there are that many since its introduction). 

Though, it does beg the (post-launch) question of using an actual full-width treatment for that content. @alexgreen Do we still have a full, edge-to-edge, treatment available? I.e., could this content -- not necessarily and image; could be a map or interactive -- work elsewhere on the page?

**Comment by phillipadsmith** [comment]
This story is still wonky, FYI: http://preview.thetyee.ca/News/2012/07/04/CarbonFootprint/
