### ISSUE TITLE
ad-blocker js broken in github repo

### ISSUE THREAD

**Issue by alexgreen** [TheTyee/design-article.thetyee.ca#340]
The ad-blocker test in aritcle_custom.js doesn't work when run locally and on github.io:

```
// add .ad-blocker if ad blocker present
if(typeof canRunAds == "undefined") {
        $("body").addClass("ad-blocker");   
}
```

The ad-blocker class is added even when no ad-blocker is active.
See: http://thetyee.github.io/design-article.thetyee.ca/library

This makes it impossible to test the placement and appearance of ads.

Can the conditional be rewritten so that it functions when run locally and from github?

**Comment by phillipadsmith** [comment]
I can look into that today.

**Comment by phillipadsmith** [comment]
Hi @alexgreen,

Can you try now. 

The `/ui/js/ads.js` script was missing.

Phillip.

**Comment by alexgreen** [comment]
I pulled those commits but it's still not working. .ad-blocker gets applied to body even when there's no ad blocker active.

I'm also noticing that the comments show in an expanded state upon page load. Seems like a js issue. possibly related?

**Comment by MrBryan** [comment]
They need to do that so that  hash links work when people get comment emails -- it loads showing then when the page completes loading, if there is no hash link, they contract

**Comment by MrBryan** [comment]
But if they stay showing then yes something is broken on develop

**Comment by alexgreen** [comment]
> if there is no hash link, they contract

Comments disclosure seems to be working now.

ad-blocker js is still misfiring.

**Comment by alexgreen** [comment]
Is the ad-blocker js in the repo different from what's on the live site? Why would it work on the live site and not in the repo?

**Comment by phillipadsmith** [comment]
> Is the ad-blocker js in the repo different from what's on the live site? Why would it work on the live site and not in the repo?

I believe this is resolved? @alexgreen Can you confirm?

**Comment by alexgreen** [comment]
no, still the same problem is evident in both develop and gh-pages.
i.e. the js applies the body class regardless of whether there's an ad-blocker active or not.

**Comment by alexgreen** [comment]
This is still broken

**Comment by alexgreen** [comment]
I've commented out the ad-blocker js since it doesn't work in the repo: dda5fecbda225eacd61b600ed4984c125e4955c5

**Comment by alexgreen** [comment]
still broken in develop
