### ISSUE TITLE
Nav bar -- adjust bottom borders

### ISSUE THREAD

**Issue by alexgreen** [TheTyee/design-article.thetyee.ca#35]
length of bottom borders (should come much closer to logo in wider viewports). Bottom borders also shouldn’t disappear in narrow views.

**Comment by kidcompassion** [comment]
Closing, as this is resolved in branch sp-based-off-ag-atomic.
<img width="857" alt="screen shot 2016-03-09 at 1 21 35 pm" src="https://cloud.githubusercontent.com/assets/1507827/13649231/e3015dec-e5f9-11e5-9032-b2ceed464cde.png">
<img width="456" alt="screen shot 2016-03-09 at 1 21 56 pm" src="https://cloud.githubusercontent.com/assets/1507827/13649238/eaf7d102-e5f9-11e5-81cb-b41c9673fc9b.png">

**Comment by alexgreen** [comment]
This is still a problem as the distance between logo and borders is not consistent. And the logo placement and sizing is also inconsistent. I'll attach a screenshot.

**Comment by alexgreen** [comment]
WIDE ISSUES:

![wide-issues](https://cloud.githubusercontent.com/assets/151099/13668291/33116826-e6ff-11e5-98a9-dba547bc12ff.png)

MEDIUM ISSUES:

![medium-issues](https://cloud.githubusercontent.com/assets/151099/13668292/3311bc72-e6ff-11e5-9c17-93ba78f1a5f3.png)

NARROW ISSUES:

![narrow-issues](https://cloud.githubusercontent.com/assets/151099/13668293/33122a86-e6ff-11e5-91d8-02fcc577dce3.png)

**Comment by kidcompassion** [comment]
Will do as soon as all functionality is completed.
